---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/janswain/git-spring-config-server-example # default
          #username: abc
          #password: abc
          search-paths:
            - 'station*'
          repos:
             local:
                pattern: '*/perf'
                uri: https://github.com/janswain/git-spring-config-server-perf # alt
                search-paths:
                 - 'station*'
security:
  basic:
    enabled: false
  user:
    name: sabre
    password: sabre